/* All free solid fontawesome icons -> https://fontawesome.com/icons?d=gallery&s=solid&m=free */

import { faOptinMonster } from '@fortawesome/free-brands-svg-icons';
import {
    faAngleDown,
    faAngleRight,
    faArrowLeft,
    faBars,
    faBookOpen,
    faBox,
    faCaretDown,
    faChartArea,
    faChartBar,
    faChartPie,
    faChevronDown,
    faChevronUp,
    faColumns,
    faEdit,
    faFileContract,
    faFilm,
    faList,
    faPlus,
    faSearch,
    faSync,
    faTable,
    faTachometerAlt,
    faTrash,
    faUser,
} from '@fortawesome/free-solid-svg-icons';

export const fontAwesomeSolidIcons = {
    faAngleDown,
    faAngleRight,
    faArrowLeft,
    faBars,
    faBookOpen,
    faChartArea,
    faChartBar,
    faChartPie,
    faChevronDown,
    faChevronUp,
    faColumns,
    faSearch,
    faTable,
    faTachometerAlt,
    faUser,
    faBox,
    faList,
    faFilm,
    faFileContract,
    faPlus,
    faOptinMonster,
    faCaretDown,
    faEdit,
    faTrash,
    faSync
};
